#!/usr/bin/env python3

import sys
import docker.errors
from dkr_core.dkr import main
from dkr_core.errors import DkrException, INVALID_INPUT, DOCKER_ERROR

try:
    main()
except DkrException as e:
    print(e.message, file=sys.stderr)
    sys.exit(e.exit_code)
except docker.errors.APIError as e:
    status_code = e.response.status_code
    message = e.response.content.decode('utf-8').strip()
    print(message, file=sys.stderr)
    if status_code < 500:
        sys.exit(INVALID_INPUT)
    else:
        sys.exit(DOCKER_ERROR)
except docker.errors.DockerException as e:
    print(e.explanation.decode('utf-8').strip(), file=sys.stderr)
    sys.exit(DOCKER_ERROR)
